name: Generar Keystore Zen

on:
  workflow_dispatch:

jobs:
  generar:
    runs-on: ubuntu-latest
    steps:
      - name: Generar keystore
        run: |
          keytool -genkeypair \
            -keystore zen.keystore \
            -alias zen \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass zen2024 \
            -keypass zen2024 \
            -dname "CN=Zen,OU=Dev,O=Zen,L=Lima,S=Lima,C=PE"

      - name: Mostrar base64
        run: |
          echo "---INICIO---"
          base64 -w 0 zen.keystore
          echo ""
          echo "---FIN---"
